# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags: [ "v*.*.*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.3'

    - name: Test
      run: go test -v ./...

    - name: Build
      run: go build -v ./...
    
    - name: save binary
      uses: actions/upload-artifact@v4.6.1
      with:
        name: nflow-generator
        path: ./nflow-generator
        overwrite: true
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: setup go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23.2'
    - name: get binaries from previous job
      uses: actions/download-artifact@v4.1.8
    - name: display downloaded files
      run: ls -R
    - name: release with binaries
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
        prerelease: ${{ endsWith(github.ref, '-alpha') || endsWith(github.ref, '-beta') }}
        files: "nflow-generator/nflow-generator"
